# Generated by Django 4.2.29 on 2026-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fot_prod',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
