# Generated by Django 4.2.29 on 2026-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_fot_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fot_usu',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
