# Generated by Django 4.2.29 on 2026-03-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_usuario_fot_usu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
