# Generated by Django 4.2.29 on 2026-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_pedidaevidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner_usu',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/banners/'),
        ),
    ]
