# Generated by Django 4.2.29 on 2026-04-09 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_prestamo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_noti', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pedido_creado', 'Pedido creado'), ('esperando_entrega', 'Esperando entrega'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('no_disponible', 'Producto no disponible'), ('aviso_devolucion', 'Aviso de devolución')], max_length=30)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('id_pedido_ref', models.PositiveIntegerField(blank=True, null=True)),
                ('fch_registro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_fk', models.ForeignKey(db_column='id_usuario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fch_registro'],
            },
        ),
    ]
