# Generated by Django 4.2.29 on 2026-04-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=30)),
                ('entidad', models.CharField(max_length=80)),
                ('entidad_id', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.TextField()),
                ('rol_usuario', models.CharField(blank=True, max_length=80, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('fch_registro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_fk', models.ForeignKey(blank=True, db_column='id_usuario_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_log',
                'ordering': ['-fch_registro', '-id_log'],
            },
        ),
    ]
