# Generated by Django 4.2.29 on 2026-04-17 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_usuario_perfil_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido_creado', 'Pedido creado'), ('esperando_entrega', 'Esperando entrega'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('no_disponible', 'Producto no disponible'), ('aviso_devolucion', 'Aviso de devolución'), ('staff_nuevo_pedido', 'Nuevo pedido recibido'), ('staff_pedido_cancelado', 'Pedido cancelado por usuario'), ('staff_pedido_entregado', 'Pedido entregado')], max_length=30),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id_reset', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token',
                'ordering': ['-creado_en', '-id_reset'],
            },
        ),
    ]
