# Generated by Django 4.2.29 on 2026-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_notificacion_tipo_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notif_vencimiento_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido_creado', 'Pedido creado'), ('esperando_entrega', 'Esperando entrega'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('no_disponible', 'Producto no disponible'), ('aviso_devolucion', 'Aviso de devolución'), ('prestamo_vencido', 'Préstamo vencido'), ('staff_nuevo_pedido', 'Nuevo pedido recibido'), ('staff_pedido_cancelado', 'Pedido cancelado por usuario'), ('staff_pedido_entregado', 'Pedido entregado')], max_length=30),
        ),
    ]
