# Generated by Django 4.2.29 on 2026-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_notif_vencimiento_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='extensiones_plazo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
