# Generated by Django 4.2.29 on 2026-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_extensiones_plazo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10),
        ),
    ]
