# Generated by Django 4.2.29 on 2026-04-21 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_tipodoc_usuario_tipo_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verificacion_sena_documento',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/validacion_manual/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_sena_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('solicitada', 'Solicitud enviada'), ('enlace_enviado', 'Enlace enviado'), ('documento_cargado', 'Documento cargado'), ('validado', 'Validado'), ('rechazada', 'Rechazada')], default='pendiente', max_length=25),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_sena_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/validacion_sena/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_sena_observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_sena_solicitada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_sena_validada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido_creado', 'Pedido creado'), ('esperando_entrega', 'Esperando entrega'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('no_disponible', 'Producto no disponible'), ('aviso_devolucion', 'Aviso de devolución'), ('prestamo_vencido', 'Préstamo vencido'), ('solicitud_validacion_sena', 'Solicitud de validación SENA'), ('enlace_validacion_sena', 'Enlace de validación SENA'), ('documento_validacion_sena', 'Documento cargado para validación SENA'), ('verificacion_sena_aprobada', 'Verificación SENA aprobada'), ('verificacion_sena_rechazada', 'Verificación SENA rechazada'), ('staff_nuevo_pedido', 'Nuevo pedido recibido'), ('staff_pedido_cancelado', 'Pedido cancelado por usuario'), ('staff_pedido_entregado', 'Pedido entregado'), ('staff_solicitud_validacion_sena', 'Solicitud manual de validación SENA'), ('staff_documento_validacion_sena', 'Documento recibido para validación SENA')], max_length=40),
        ),
        migrations.CreateModel(
            name='VerificacionSenaToken',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacion_sena_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verificacion_sena_token',
                'ordering': ['-creado_en', '-id_token'],
            },
        ),
    ]
