# Generated by Django 4.2.29 on 2026-05-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_productofoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido_creado', 'Pedido creado'), ('esperando_entrega', 'Esperando entrega'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('no_disponible', 'Producto no disponible'), ('aviso_devolucion', 'Aviso de devolución'), ('prestamo_vencido', 'Préstamo vencido'), ('solicitud_validacion_sena', 'Solicitud de validación SENA'), ('enlace_validacion_sena', 'Enlace de validación SENA'), ('documento_validacion_sena', 'Documento cargado para validación SENA'), ('verificacion_sena_aprobada', 'Verificación SENA aprobada'), ('verificacion_sena_rechazada', 'Verificación SENA rechazada'), ('actualizar_tipo_doc', 'Actualizar tipo de documento'), ('staff_nuevo_pedido', 'Nuevo pedido recibido'), ('staff_pedido_cancelado', 'Pedido cancelado por usuario'), ('staff_pedido_entregado', 'Pedido entregado'), ('staff_solicitud_validacion_sena', 'Solicitud manual de validación SENA'), ('staff_documento_validacion_sena', 'Documento recibido para validación SENA')], max_length=40),
        ),
    ]
