# Generated by Django 4.2.29 on 2026-05-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_importacioninventariolog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['id_cat_fk_id', 'subcategoria_padre_id', 'nombre_subcategoria']},
        ),
        migrations.RemoveConstraint(
            model_name='subcategoria',
            name='uq_subcat_catalogo_nombre',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subcategoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='inventario.subcategoria'),
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('id_cat_fk', 'subcategoria_padre', 'nombre_subcategoria'), name='uq_subcat_catalogo_padre_nombre'),
        ),
    ]
