# Generated by Django 4.2.29 on 2026-05-30 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_pedido_motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionProducto',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('fch_registro', models.DateTimeField(blank=True, null=True)),
                ('fch_ult_act', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ubicacion_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='catalogo',
            name='id_ubicacion_fk',
            field=models.ForeignKey(blank=True, db_column='id_ubicacion_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogos', to='inventario.ubicacionproducto'),
        ),
    ]
