# Generated by Django 4.2.29 on 2026-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_subcategoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='codigo_macro',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('id_cat_fk', 'subcategoria_padre', 'codigo_clasificacion'), name='uq_subcat_catalogo_padre_codigo'),
        ),
    ]
