# Generated by Django 4.2.29 on 2026-06-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_alter_catalogo_codigo_macro_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subcategoria',
            name='uq_subcat_catalogo_padre_nombre',
        ),
    ]
